<h1 style="text-align: center;">请分别给出红绿蓝选中的数字</h1>

<img src="./images/quize-access1.jpg"  width="500" height="600">

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
box = np.arange(1,31).reshape((6,5))
box

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [3]:
box[2:4,0:2] # blue

array([[11, 12],
       [16, 17]])

In [4]:
 # green

array([ 2,  8, 14, 20])

In [5]:
 # red

array([[ 4,  5],
       [24, 25],
       [29, 30]])