### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

creating arrays, shape, size and data type

In [2]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
# print(b)
b

array([[9., 8., 7.],
       [6., 5., 4.]])

**作为一个数组，NumPy 有一些常用属性，如：数组维度(ndim)、数据类型(dtype)、形状(shape)、Size 等**

In [4]:
# Get Dimension
print(a.ndim, b.ndim)

1 2


In [5]:
# Get Type
print(a.dtype, b.dtype)

int32 float64


In [6]:
# Get Shape
b.shape

(2, 3)

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get number of elements
a.size

3

In [10]:
# Get total size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns, etc

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [r, c]
a[1, 5]

13

In [15]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [16]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [17]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3 Dimension Example

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get specific element (work outside in)
b[0,1,1]

4

In [21]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [22]:
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [23]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [25]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [26]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.51474157, 0.37696012],
       [0.42517207, 0.16619487],
       [0.58429871, 0.74494025],
       [0.8677725 , 0.81915037]])

In [28]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 2,  0,  1],
       [-2,  1,  0],
       [ 2, -2,  3]])

In [29]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [32]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics
For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [33]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
a + 2

array([3, 4, 5, 6])

In [35]:
a - 2

array([-1,  0,  1,  2])

In [36]:
a * 2

array([2, 4, 6, 8])

In [37]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [38]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [39]:
a ** 2

array([ 1,  4,  9, 16])

In [40]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [41]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# np.info(np.matmul)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [42]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [43]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

#### Statistics

In [44]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats)

1

In [46]:
np.max(stats, axis=1)

array([3, 6])

In [47]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [48]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before, before.shape)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [51]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [52]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [53]:
## You can index with a list of NumPy
a = np.asarray([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [54]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [55]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])